from sqlalchemy import Column, Text, Integer, DateTime, ForeignKey, UniqueConstraint, Boolean, Float
from sqlalchemy.dialects.postgresql import JSONB
from pgvector.sqlalchemy import Vector
from backend.db.base import Base


class Post(Base):
    __tablename__ = "posts"
    __table_args__ = (UniqueConstraint("url", "period_label", name="uq_post_url_period"),)

    id = Column(Text, primary_key=True)             # sha256(url + period_label)
    source_post_id = Column(Text)
    short_code = Column(Text)
    owner_username = Column(Text, index=True)
    owner_full_name = Column(Text)
    owner_id = Column(Text)
    owner_profile_pic_url = Column(Text)
    location_name = Column(Text)
    location_id = Column(Text)
    url = Column(Text, nullable=False)
    timestamp = Column(DateTime(timezone=True))
    likes_count = Column(Integer, default=0)
    video_play_count = Column(Integer, default=0)
    video_view_count = Column(Integer, default=0)
    type = Column(Text)
    video_url = Column(Text)
    audio_url = Column(Text)
    video_duration = Column(Float)
    display_url = Column(Text)
    display_storage_path = Column(Text)
    display_storage_url = Column(Text)
    dimensions_height = Column(Integer)
    dimensions_width = Column(Integer)
    is_comments_disabled = Column(Boolean, default=False)
    alt = Column(Text)
    caption = Column(Text)
    product_type = Column(Text)
    input_url = Column(Text)
    comments_count = Column(Integer, default=0)
    first_comment = Column(Text)
    latest_comments = Column(JSONB, default=list)
    images = Column(JSONB, default=list)
    child_posts = Column(JSONB, default=list)
    music_info = Column(JSONB, default=dict)
    hashtags = Column(JSONB, default=list)
    mentions = Column(JSONB, default=list)
    tagged_users = Column(JSONB, default=list)
    coauthor_producers = Column(JSONB, default=list)
    is_pinned = Column(Boolean, default=False)
    profile_id = Column(Text, ForeignKey("profiles.id", ondelete="SET NULL"), nullable=True, index=True)
    scraped_at = Column(DateTime(timezone=True))
    period_label = Column(Text, nullable=False, index=True)
    run_id = Column(Integer, ForeignKey("scrape_runs.id"), nullable=True)
    embedding = Column(Vector(1536))
